version: 2

jobs:
  build: &buildjob
    docker:
      - image: circleci/golang:1.9.4-stretch
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install packet cli and tools
          command: |
            docker create --name packet ebsarr/packet
            docker cp packet:/usr/local/bin/packet ./packet
            sudo mv ./packet /usr/local/bin/packet
            packet -v
            sudo apt-get update && sudo apt-get install -y --no-install-recommends jq unzip curl
            jq --version
            curl -o terraform.zip https://releases.hashicorp.com/terraform/0.11.14/terraform_0.11.14_linux_amd64.zip
            sudo unzip -d /usr/bin terraform.zip
            rm terraform.zip
            terraform --version

      - add_ssh_keys:
          fingerprints:
            - "1f:c6:3d:0b:c0:17:58:c2:f9:9d:e4:ab:ea:af:fe:96"
      - run:
          name: Use my key
          command: |
            [ ~/.ssh/id_rsa_1fc63d0bc01758c2f99de4abeaaffe96 ] && cp ~/.ssh/id_rsa_1fc63d0bc01758c2f99de4abeaaffe96 ~/.ssh/id_rsa

      - run:
          name: Provisioning a packer build machine
          command: |
            ./machine.sh create circle${CIRCLE_BUILD_NUM} ${HYPERVISOR}

      - run:
          name: Run packer build
          command: |
            ./build.sh circle${CIRCLE_BUILD_NUM} ${PACKER_TEMPLATE} ${HYPERVISOR}
          no_output_timeout: 9000

  upload: &uploadjob
    docker:
      - image: microsoft/azure-cli:0.10.14
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout

      - run:
          name: Install tools
          command: |
            apt-get update && apt-get install -y jq curl
            azure --version
            jq --version
            curl --version

      - run:
          name: Upload to Vagrant Cloud
          command: |
            ./upload.sh ${PACKER_TEMPLATE} ${HYPERVISOR}
          no_output_timeout: 3600

  windows_2019_docker:
    <<: *buildjob
    environment:
      - PACKER_TEMPLATE: "windows_2019_docker"
      - PACKET_PLAN: "baremetal_1"
      - HYPERVISOR: "virtualbox+vmware"

  windows_2019_docker_hyperv:
    <<: *buildjob
    environment:
      - PACKER_TEMPLATE: "windows_2019_docker"
      - AZURE_PLAN: "Standard_E4s_v3"
      - HYPERVISOR: "hyperv"

  windows_2019_docker_azure:
    <<: *buildjob
    environment:
      - PACKER_TEMPLATE: "windows_2019_docker_azure"
      - AZURE_PLAN: "Standard_E4s_v3"
      - HYPERVISOR: "azure"

  windows_2019:
    <<: *buildjob
    environment:
      - PACKER_TEMPLATE: "windows_2019"
      - PACKET_PLAN: "baremetal_1"
      - HYPERVISOR: "virtualbox+vmware"

  windows_2019_hyperv:
    <<: *buildjob
    environment:
      - PACKER_TEMPLATE: "windows_2019"
      - AZURE_PLAN: "Standard_E4s_v3"
      - HYPERVISOR: "hyperv"

  windows_2022:
    <<: *buildjob
    environment:
      - PACKER_TEMPLATE: "windows_2022"
      - PACKET_PLAN: "baremetal_1"
      - HYPERVISOR: "virtualbox+vmware"

  windows_2022_hyperv:
    <<: *buildjob
    environment:
      - PACKER_TEMPLATE: "windows_2022"
      - AZURE_PLAN: "Standard_E4s_v3"
      - HYPERVISOR: "hyperv"

  windows_10:
    <<: *buildjob
    environment:
      - PACKER_TEMPLATE: "windows_10"
      - PACKET_PLAN: "baremetal_1"
      - HYPERVISOR: "virtualbox+vmware"

  windows_10_hyperv:
    <<: *buildjob
    environment:
      - PACKER_TEMPLATE: "windows_10"
      - AZURE_PLAN: "Standard_E4s_v3"
      - HYPERVISOR: "hyperv"

  upload_windows_2019_docker_hyperv:
    <<: *uploadjob
    environment:
      - PACKER_TEMPLATE: "windows_2019_docker"
      - HYPERVISOR: "hyperv"

  upload_windows_2019_docker_virtualbox:
    <<: *uploadjob
    environment:
      - PACKER_TEMPLATE: "windows_2019_docker"
      - HYPERVISOR: "virtualbox"

  upload_windows_2019_docker_vmware:
    <<: *uploadjob
    environment:
      - PACKER_TEMPLATE: "windows_2019_docker"
      - HYPERVISOR: "vmware"

  upload_windows_2019_virtualbox:
    <<: *uploadjob
    environment:
      - PACKER_TEMPLATE: "windows_2019"
      - HYPERVISOR: "virtualbox"

  upload_windows_2019_vmware:
    <<: *uploadjob
    environment:
      - PACKER_TEMPLATE: "windows_2019"
      - HYPERVISOR: "vmware"

  upload_windows_10_hyperv:
    <<: *uploadjob
    environment:
      - PACKER_TEMPLATE: "windows_10"
      - HYPERVISOR: "hyperv"

  upload_windows_10_virtualbox:
    <<: *uploadjob
    environment:
      - PACKER_TEMPLATE: "windows_10"
      - HYPERVISOR: "virtualbox"

  upload_windows_10_vmware:
    <<: *uploadjob
    environment:
      - PACKER_TEMPLATE: "windows_10"
      - HYPERVISOR: "vmware"

  cleanup:
    docker:
      - image: circleci/golang:1.9.4-stretch
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install packet cli and tools
          command: |
            docker create --name packet ebsarr/packet
            docker cp packet:/usr/local/bin/packet ./packet
            sudo mv ./packet /usr/local/bin/packet
            packet -v
            sudo apt-get update && sudo apt-get install -y --no-install-recommends jq unzip curl
            jq --version

      - run:
          name: Cleanup old cloud machines
          command: |
            ./machine.sh cleanup
    
workflows:
  version: 2
  build_10:
    jobs:
      - windows_10
  # build_2019:
  #   jobs:
  #     - windows_2019
  # build_2019_docker:
  #   jobs:
  #     - windows_2019_docker
  # build_2022:
  #   jobs:
  #     - windows_2022
  # upload_windows_10:
  #   jobs:
  #     - upload_windows_10_virtualbox
  #     - upload_windows_10_vmware
  # upload_2019:
  #   jobs:
  #     - upload_windows_2019_virtualbox
  #     - upload_windows_2019_vmware
  # upload_2019_docker:
  #   jobs:
  #     - upload_windows_2019_docker_virtualbox
  #     - upload_windows_2019_docker_vmware

  cleanup:
    jobs:
      - cleanup
    triggers:
      - schedule:
          cron: "32 1 * * *"
          filters:
            branches:
              only:
                - main
