name: Build

on:
  push:
    branches:
      - main

jobs:

  build:
 
    runs-on: ubuntu-latest
    env:
      PACKER_TEMPLATE: windows_10
      PACKET_PLAN: baremetal_1
      HYPERVISOR: virtualbox+vmware
 
    steps:
    - uses: actions/checkout@v2
    - name: Install tools
      run: |
        docker create --name packet ebsarr/packet
        docker cp packet:/usr/local/bin/packet ./packet
        sudo mv ./packet /usr/local/bin/packet
        packet -v
        jq --version
        curl --version
    - name: Provision a packer build machine
      run: ./machine.sh create github${GITHUB_RUN_NUMBER} ${HYPERVISOR}
    - name: Run packer build
      run: ./build.sh github${GITHUB_RUN_NUMBER} ${PACKER_TEMPLATE} ${HYPERVISOR}
